In [1]:
import torch

In [2]:
# torch.empty(2, 3) 是一个PyTorch中的函数调用，它用来创建一个张量（tensor），
# 具有指定的形状（在这个例子中是2行3列），但其中的数据是未初始化的，意味着张量中的元素值是随机的，取决于内存的状态
torch.empty(2, 3)

tensor([[6.4658e-27, 7.4549e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
# torch.rand() 会创建均匀分布于[0, 1)之间的随机张量
torch.rand(2, 3)

tensor([[0.1203, 0.0821, 0.8574],
        [0.3153, 0.5997, 0.0999]])

In [6]:
# torch.randn() 会创建服从标准正态分布的随机张量
torch.randn(2, 3)

tensor([[-1.1532, -0.2449,  0.1435],
        [ 0.0815, -0.9043, -1.0324]])

In [8]:
torch.zeros(2, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [9]:
torch.zeros(2, 3, dtype=torch.double)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [10]:
# torch.arange(10) 是一个PyTorch函数调用，用于创建一个一维张量，其中包含从0开始（默认），
# 步长为1的一系列整数，直到指定的结束值（但不包括该值）。在这个例子中，它将生成一个包含0到9的整数张量
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array = [[1.0, 3.8, 2.1], [8.6, 4.0, 2.4]]

In [12]:
# torch.tensor() 或者 torch.from_numpy() 基于已有的数组或 Numpy 数组创建张量
torch.tensor(array)

tensor([[1.0000, 3.8000, 2.1000],
        [8.6000, 4.0000, 2.4000]])

In [14]:
import numpy as np
array = np.array([[1.0, 3.8, 2.1], [8.6, 4.0, 2.4]])
torch.from_numpy(array)

tensor([[1.0000, 3.8000, 2.1000],
        [8.6000, 4.0000, 2.4000]], dtype=torch.float64)

In [20]:
x = torch.tensor([1, 2, 3], dtype=torch.double)
y = torch.tensor([4, 5, 6], dtype=torch.double)
print(x + y)
print(x - y)
print(x * y)
print(x / y)

tensor([5., 7., 9.], dtype=torch.float64)
tensor([-3., -3., -3.], dtype=torch.float64)
tensor([ 4., 10., 18.], dtype=torch.float64)
tensor([0.2500, 0.4000, 0.5000], dtype=torch.float64)


In [21]:
# torch.dot() 计算向量点积、torch.mm() 计算矩阵相乘
x.dot(y)

tensor(32., dtype=torch.float64)

In [22]:
x.sin()

tensor([0.8415, 0.9093, 0.1411], dtype=torch.float64)

In [23]:
#指数计算
x.exp()

tensor([ 2.7183,  7.3891, 20.0855], dtype=torch.float64)

In [24]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.double)

In [25]:
# 平均值
x.mean()

tensor(3.5000, dtype=torch.float64)

In [26]:
# 该函数用于计算PyTorch张量x在指定维度dim=0上的平均值。


x.mean(dim=0)

tensor([2.5000, 3.5000, 4.5000], dtype=torch.float64)

In [28]:
# 该函数用于计算PyTorch张量x在指定维度dim=1上的平均值。
x.mean(dim=1)

tensor([2., 5.], dtype=torch.float64)

In [30]:
x.mean(dim=1, keepdim=True)

tensor([[2.],
        [5.]], dtype=torch.float64)

In [29]:
x.mean(dim=0, keepdim=True)

tensor([[2.5000, 3.5000, 4.5000]], dtype=torch.float64)

In [36]:
x = torch.tensor([[1, 2, 3], [ 4,  5,  6]], dtype=torch.double)
y = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.double)

In [37]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [32]:
torch.cat((x, y), dim=0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64)

In [33]:
torch.cat((x, y), dim=1)

tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]], dtype=torch.float64)

In [35]:
import torch
import timeit

M = torch.rand(1000, 1000)
print(timeit.timeit(lambda: M.mm(M).mm(M), number=5000))

# N = torch.rand(1000, 1000).cuda()
# print(timeit.timeit(lambda: N.mm(N).mm(N), number=5000))

52.301571400000284
